-- Migration 093: Authoritative permissions reset — derived strictly from backend route role arrays
--
-- Source of truth for each role:  which const *_WRITE / *_ADMIN arrays it appears in
--   BILLING_WRITE/ADMIN   billing.js, billing-operations.js
--   AP_WRITE/ADMIN        payments.js
--   FINANCE_WRITE/ADMIN   finance.js
--   VENDOR_WRITE/ADMIN    vendors.js
--   GRN_WRITE/ADMIN       grn.js
--   ITEM_WRITE            item-master.js
--   ASSET_WRITE/ADMIN     asset-management.js
--   PROC_WRITE/ADMIN      procurement.js, payments.js
--   HR_WRITE              payroll.js
--   PAYROLL_ADMIN         payroll.js
--   USER_ADMIN_ROLES      users.js
--   COA_WRITE_ROLES       chart-of-accounts.js
--
-- New permissions added (existed in routes, missing from DB):
--   BILLING_DELETE   — billing-operations.js DELETE_BILL  = [SUPER_ADMIN, CENTER_MANAGER, FINANCE_MANAGER]
--   BILLING_DISCOUNT — billing-operations.js APPLY_DISCOUNT = [SUPER_ADMIN, CENTER_MANAGER, FINANCE_MANAGER, ACCOUNTANT]
--   BILLING_REFUND   — billing-operations.js PROCESS_REFUND = [SUPER_ADMIN, CENTER_MANAGER, FINANCE_MANAGER, ACCOUNTANT]
--   ASSET_DISPOSE    — asset-management.js   ASSET_ADMIN  = [SUPER_ADMIN, CENTER_MANAGER, FINANCE_MANAGER]
--
-- Fixes: PO_APPROVE duplicate in PROCUREMENT_MANAGER

-- ── SUPER_ADMIN ───────────────────────────────────────────────────────────────
UPDATE user_roles SET permissions = '["ALL_ACCESS"]'::jsonb WHERE role = 'SUPER_ADMIN';

-- ── CENTER_MANAGER ────────────────────────────────────────────────────────────
-- Appears in: USER_ADMIN, BILLING_WRITE, BILLING_ADMIN, AP_WRITE, AP_ADMIN,
--   FINANCE_WRITE, FINANCE_ADMIN, HR_WRITE, PAYROLL_ADMIN, ASSET_WRITE, ASSET_ADMIN,
--   VENDOR_WRITE, VENDOR_ADMIN, GRN_WRITE, GRN_ADMIN, ITEM_WRITE, CATEGORY_WRITE,
--   COA_WRITE_ROLES, PROC_WRITE, PROC_ADMIN, PROC_APPROVE
UPDATE user_roles SET permissions = '[
  "USER_VIEW","USER_CREATE","USER_UPDATE","USER_ASSIGN_ROLE",
  "PATIENT_VIEW","PATIENT_CREATE","PATIENT_UPDATE","PATIENT_BILLING","PATIENT_INSURANCE",
  "STUDY_VIEW","STUDY_CREATE","STUDY_UPDATE","STUDY_REPORT","STUDY_ASSIGN_RADIOLOGIST",
  "RADIOLOGIST_VIEW","RADIOLOGIST_CREATE","RADIOLOGIST_UPDATE","RADIOLOGIST_PAYMENT",
  "BILLING_VIEW","BILLING_CREATE","BILLING_UPDATE","BILLING_DELETE","BILLING_PRINT",
  "BILLING_PAYMENT","BILLING_DISCOUNT","BILLING_REFUND",
  "JE_VIEW","JE_CREATE","JE_POST","JE_REVERSE",
  "COA_VIEW","COA_CREATE","COA_UPDATE","COA_DELETE",
  "PETTY_CASH_VIEW","PETTY_CASH_CREATE","PETTY_CASH_APPROVE",
  "VENDOR_VIEW","VENDOR_CREATE","VENDOR_UPDATE","VENDOR_BILLING","VENDOR_PAYMENT",
  "INVENTORY_VIEW","INVENTORY_CREATE","INVENTORY_UPDATE","INVENTORY_PURCHASE","INVENTORY_STOCK",
  "PR_VIEW","PR_CREATE","PR_APPROVE_L1","PR_APPROVE_L2",
  "PO_VIEW","PO_CREATE","PO_APPROVE","PO_CANCEL",
  "GRN_VIEW","GRN_CREATE","GRN_APPROVE",
  "ASSET_VIEW","ASSET_CREATE","ASSET_UPDATE","ASSET_DISPOSE",
  "EMPLOYEE_VIEW","EMPLOYEE_CREATE","EMPLOYEE_UPDATE","EMPLOYEE_ATTENDANCE","EMPLOYEE_PAYROLL",
  "PAYROLL_VIEW","PAYROLL_RUN","PAYROLL_APPROVE",
  "CENTER_VIEW","CENTER_UPDATE",
  "REPORTS_VIEW","REPORTS_BILLING","REPORTS_FINANCIAL","REPORTS_PATIENT",
  "REPORTS_RADIOLOGY","REPORTS_EMPLOYEE","REPORTS_DOWNLOAD",
  "DASHBOARD_VIEW","DASHBOARD_ADMIN","DASHBOARD_FINANCIAL","DASHBOARD_CLINICAL","DASHBOARD_OPERATIONAL"
]'::jsonb WHERE role = 'CENTER_MANAGER';

-- ── FINANCE_MANAGER ───────────────────────────────────────────────────────────
-- Appears in: BILLING_WRITE, BILLING_ADMIN, AP_WRITE, AP_ADMIN,
--   FINANCE_WRITE, FINANCE_ADMIN, ASSET_WRITE, ASSET_ADMIN,
--   VENDOR_WRITE, VENDOR_ADMIN, GRN_WRITE, GRN_ADMIN, ITEM_WRITE, CATEGORY_WRITE,
--   COA_WRITE_ROLES, PROC_WRITE, PROC_ADMIN, PROC_APPROVE
UPDATE user_roles SET permissions = '[
  "BILLING_VIEW","BILLING_CREATE","BILLING_UPDATE","BILLING_DELETE","BILLING_PRINT",
  "BILLING_PAYMENT","BILLING_DISCOUNT","BILLING_REFUND",
  "JE_VIEW","JE_CREATE","JE_POST","JE_REVERSE",
  "COA_VIEW","COA_CREATE","COA_UPDATE","COA_DELETE",
  "PETTY_CASH_VIEW","PETTY_CASH_CREATE","PETTY_CASH_APPROVE",
  "VENDOR_VIEW","VENDOR_CREATE","VENDOR_UPDATE","VENDOR_BILLING","VENDOR_PAYMENT",
  "INVENTORY_VIEW","INVENTORY_CREATE","INVENTORY_UPDATE","INVENTORY_PURCHASE","INVENTORY_STOCK",
  "PR_VIEW","PR_CREATE","PR_APPROVE_L1","PR_APPROVE_L2",
  "PO_VIEW","PO_CREATE","PO_APPROVE","PO_CANCEL",
  "GRN_VIEW","GRN_CREATE","GRN_APPROVE",
  "ASSET_VIEW","ASSET_CREATE","ASSET_UPDATE","ASSET_DISPOSE",
  "EMPLOYEE_VIEW","EMPLOYEE_PAYROLL",
  "REPORTS_VIEW","REPORTS_BILLING","REPORTS_FINANCIAL","REPORTS_DOWNLOAD",
  "DASHBOARD_VIEW","DASHBOARD_FINANCIAL"
]'::jsonb WHERE role = 'FINANCE_MANAGER';

-- ── ACCOUNTANT ────────────────────────────────────────────────────────────────
-- Appears in: BILLING_WRITE, BILLING_ADMIN, AP_WRITE, FINANCE_WRITE,
--   PROC_WRITE, VENDOR_WRITE
UPDATE user_roles SET permissions = '[
  "BILLING_VIEW","BILLING_CREATE","BILLING_UPDATE","BILLING_DELETE","BILLING_PRINT",
  "BILLING_PAYMENT","BILLING_DISCOUNT","BILLING_REFUND",
  "JE_VIEW","JE_CREATE",
  "COA_VIEW",
  "PETTY_CASH_VIEW","PETTY_CASH_CREATE","PETTY_CASH_APPROVE",
  "VENDOR_VIEW","VENDOR_CREATE","VENDOR_UPDATE","VENDOR_BILLING","VENDOR_PAYMENT",
  "INVENTORY_VIEW",
  "RADIOLOGIST_VIEW","RADIOLOGIST_PAYMENT",
  "EMPLOYEE_VIEW","EMPLOYEE_PAYROLL",
  "REPORTS_VIEW","REPORTS_BILLING","REPORTS_FINANCIAL","REPORTS_DOWNLOAD",
  "DASHBOARD_VIEW","DASHBOARD_FINANCIAL"
]'::jsonb WHERE role = 'ACCOUNTANT';

-- ── HR_MANAGER ────────────────────────────────────────────────────────────────
-- Appears in: HR_WRITE, USER_ADMIN_ROLES
UPDATE user_roles SET permissions = '[
  "USER_VIEW","USER_CREATE","USER_UPDATE","USER_ASSIGN_ROLE",
  "EMPLOYEE_VIEW","EMPLOYEE_CREATE","EMPLOYEE_UPDATE","EMPLOYEE_ATTENDANCE","EMPLOYEE_PAYROLL",
  "PAYROLL_VIEW","PAYROLL_RUN","PAYROLL_APPROVE",
  "REPORTS_VIEW","REPORTS_EMPLOYEE","REPORTS_DOWNLOAD",
  "DASHBOARD_VIEW","DASHBOARD_ADMIN","DASHBOARD_OPERATIONAL"
]'::jsonb WHERE role = 'HR_MANAGER';

-- ── RADIOLOGIST ───────────────────────────────────────────────────────────────
UPDATE user_roles SET permissions = '[
  "PATIENT_VIEW",
  "STUDY_VIEW","STUDY_REPORT",
  "REPORTS_VIEW","REPORTS_RADIOLOGY",
  "DASHBOARD_VIEW","DASHBOARD_CLINICAL"
]'::jsonb WHERE role = 'RADIOLOGIST';

-- ── TECHNICIAN ────────────────────────────────────────────────────────────────
UPDATE user_roles SET permissions = '[
  "PATIENT_VIEW","PATIENT_CREATE","PATIENT_UPDATE",
  "STUDY_VIEW","STUDY_CREATE","STUDY_UPDATE","STUDY_ASSIGN_RADIOLOGIST",
  "REPORTS_VIEW","REPORTS_RADIOLOGY",
  "DASHBOARD_VIEW","DASHBOARD_CLINICAL","DASHBOARD_OPERATIONAL"
]'::jsonb WHERE role = 'TECHNICIAN';

-- ── LAB_TECHNICIAN ────────────────────────────────────────────────────────────
UPDATE user_roles SET permissions = '[
  "PATIENT_VIEW",
  "STUDY_VIEW","STUDY_CREATE","STUDY_UPDATE","STUDY_REPORT",
  "BILLING_VIEW","BILLING_CREATE","BILLING_UPDATE","BILLING_PRINT","BILLING_PAYMENT",
  "REPORTS_VIEW","REPORTS_RADIOLOGY",
  "DASHBOARD_VIEW","DASHBOARD_CLINICAL"
]'::jsonb WHERE role = 'LAB_TECHNICIAN';

-- ── RECEPTIONIST ──────────────────────────────────────────────────────────────
UPDATE user_roles SET permissions = '[
  "PATIENT_VIEW","PATIENT_CREATE","PATIENT_UPDATE","PATIENT_BILLING","PATIENT_INSURANCE",
  "BILLING_VIEW","BILLING_CREATE","BILLING_UPDATE","BILLING_PRINT","BILLING_PAYMENT","BILLING_CANCEL_OWN",
  "REPORTS_VIEW","REPORTS_BILLING","REPORTS_PATIENT",
  "DASHBOARD_VIEW","DASHBOARD_ADMIN","DASHBOARD_FINANCIAL"
]'::jsonb WHERE role = 'RECEPTIONIST';

-- ── INVENTORY_MANAGER ─────────────────────────────────────────────────────────
-- Appears in: ASSET_WRITE, VENDOR_WRITE, GRN_WRITE, ITEM_WRITE, PROC_WRITE
-- Can create/submit PRs but NOT approve them (no PR_APPROVE_L1/L2)
UPDATE user_roles SET permissions = '[
  "VENDOR_VIEW","VENDOR_CREATE","VENDOR_UPDATE","VENDOR_BILLING","VENDOR_PAYMENT",
  "INVENTORY_VIEW","INVENTORY_CREATE","INVENTORY_UPDATE","INVENTORY_PURCHASE","INVENTORY_STOCK",
  "PR_VIEW","PR_CREATE",
  "PO_VIEW","PO_CREATE","PO_APPROVE","PO_CANCEL",
  "GRN_VIEW","GRN_CREATE","GRN_APPROVE",
  "ASSET_VIEW","ASSET_CREATE","ASSET_UPDATE",
  "REPORTS_VIEW","REPORTS_DOWNLOAD",
  "DASHBOARD_VIEW","DASHBOARD_OPERATIONAL"
]'::jsonb WHERE role = 'INVENTORY_MANAGER';

-- ── PROCUREMENT_MANAGER ───────────────────────────────────────────────────────
-- Appears in: ASSET_WRITE, VENDOR_WRITE, GRN_WRITE, ITEM_WRITE,
--   PROC_WRITE, PROC_ADMIN, PROC_APPROVE
-- Full procurement authority including PR approval at both levels
UPDATE user_roles SET permissions = '[
  "VENDOR_VIEW","VENDOR_CREATE","VENDOR_UPDATE","VENDOR_BILLING","VENDOR_PAYMENT",
  "INVENTORY_VIEW","INVENTORY_CREATE","INVENTORY_UPDATE","INVENTORY_PURCHASE","INVENTORY_STOCK",
  "PR_VIEW","PR_CREATE","PR_APPROVE_L1","PR_APPROVE_L2",
  "PO_VIEW","PO_CREATE","PO_APPROVE","PO_CANCEL",
  "GRN_VIEW","GRN_CREATE","GRN_APPROVE",
  "ASSET_VIEW","ASSET_CREATE","ASSET_UPDATE","ASSET_DISPOSE",
  "REPORTS_VIEW","REPORTS_DOWNLOAD",
  "DASHBOARD_VIEW","DASHBOARD_OPERATIONAL"
]'::jsonb WHERE role = 'PROCUREMENT_MANAGER';
